---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bjjeire-api
  namespace: bjj-app
spec:
  image: ghcr.io/ianoflynnautomation/bjjeire-api
  interval: 5m
  secretRef:
    name: ghcr-pull-secret

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bjjeire-frontend
  namespace: bjj-app
spec:
  image: ghcr.io/ianoflynnautomation/bjjeire-frontend
  interval: 5m
  secretRef:
    name: ghcr-pull-secret

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bjjeire-seeder
  namespace: bjj-app
spec:
  image: ghcr.io/ianoflynnautomation/bjjeire-seeder
  interval: 5m
  secretRef:
    name: ghcr-pull-secret
