---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: bjj-eire
  namespace: bjjeire-app
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxbot@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |
        chore(flux): update bjj-eire image tags (${CLUSTER_ID})

        {{ range $resource, $changes := .Changed.Objects -}}
        {{ range $changes -}}
        - {{ $resource.Kind }}/{{ $resource.Name }}: {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
        {{ end -}}
    push:
      branch: main
  update:
    path: "./kubernetes/apps/overlays/${CLUSTER_ID}/bjj-eire"
    strategy: Setters
