---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bjjeire-app

resources:
  - ocirepository.yaml
  - externalsecrets.yaml
  - helmrelease.yaml
  - httproute.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - grafanadashboard.yaml
  - mongodb-exporter.yaml
  - mongodb-servicemonitor.yaml
  # - mongodb-prometheusrule.yaml
  - mongodb-grafanadashboard.yaml
  - request-authentication.yaml
