---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: bjj-api-entra-jwt
  namespace: bjj-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bjj-api
  jwtRules:
    - issuer: "https://login.microsoftonline.com/${TENANT_ID}/v2.0"
      jwksUri: "https://login.microsoftonline.com/${TENANT_ID}/discovery/v2.0/keys"
      forwardOriginalToken: true
