---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-preview-webhook
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: flux-preview-webhook
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  data:
    - secretKey: token
      remoteRef:
        key: flux-preview-webhook-token
