---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-preview-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: github-preview-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: git
        password: "{{ .token }}"
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  data:
    - secretKey: token
      remoteRef:
        key: github-preview-pat
