---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - externalsecret-github.yaml
  - externalsecret-webhook.yaml
  - inputprovider.yaml
  - resourceset.yaml
  - receiver.yaml

configMapGenerator:
  - name: bjj-eire-ephemeral-values
    files:
      - values.yaml=values-ephemeral.yaml
    options:
      disableNameSuffixHash: true
      annotations:
        reconcile.fluxcd.io/watch: Enabled
