---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-preview
  namespace: flux-system
  labels:
    app.kubernetes.io/name: bjj-eire-preview
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
