---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: github-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_app_id: "{{ .appId }}"
        github_app_installation_id: "{{ .installationId }}"
        github_app_private_key: "{{ .privateKey }}"
  data:
    - secretKey: appId
      remoteRef:
        key: github-app-id
    - secretKey: installationId
      remoteRef:
        key: github-app-installation-id
    - secretKey: privateKey
      remoteRef:
        key: github-app-private-key
