---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - helmrelease.yaml
  - helmrelease-bjjeire.yaml
  - helmrelease-bjjeire-tests.yaml
  - ocirepository.yaml
  - externalsecret.yaml
