---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pr-env-janitor
  namespace: pr-env-janitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pr-env-janitor
rules:

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pr-env-janitor
subjects:
  - kind: ServiceAccount
    name: pr-env-janitor
    namespace: pr-env-janitor
roleRef:
  kind: ClusterRole
  name: pr-env-janitor
  apiGroup: rbac.authorization.k8s.io
