---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: caa-records
  namespace: network-system
  annotations:
    external-dns.alpha.kubernetes.io/external: "true"
spec:
  endpoints:
    - dnsName: "${CLUSTER_DOMAIN}"
      recordType: CAA
      recordTTL: 3600
      targets:
        - "0 issue \"letsencrypt.org\""
        - "0 issuewild \"letsencrypt.org\""
        - "0 iodef \"mailto:${PRIVATE_EMAIL}\""
