---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - grafanadashboard.yaml  # Disabled - requires GrafanaDashboard CRD from grafana-operator
  - dnsendpoint-crd.yaml
  - helmrelease.yaml
  - ocirepository.yaml
  - caa-records.yaml
  # - prometheusrule.yaml

configMapGenerator:
  - name: external-dns-values
    namespace: network-system
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
