---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: network-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        TUNNEL_TOKEN: "{{ .TUNNEL_TOKEN }}"
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: cloudflare-tunnel-token
