---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bjj-eire
  namespace: bjjeire-app
spec:
  values:
    bjj-api:
      api:
        image:
          tag: v0.1.14
    bjj-frontend:
      frontend:
        image:
          tag: v0.1.23
    seeder:
      image:
        tag: v0.1.11
