---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bjj-eire
  namespace: bjjeire-app
spec:
  values:
    seeder:
      dataset: "test"
    bjj-mongodb:
      mongodb:
        persistence:
          storageClassName: default
          size: 10Gi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
    bjj-api:
      api:
        replicaCount: 1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ""
          ASPNETCORE_ENVIRONMENT: Development
          OTEL_RESOURCE_ATTRIBUTES__deployment.environment: dev
          ServiceDefaults__EnablePrometheus: "false"
          RateLimitOptions__PermitLimit: "30"
          RateLimitOptions__WindowInSeconds: "10"
        podAnnotations:
          prometheus.io/scrape: "false"
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 50m
            memory: 128Mi
        autoscaling:
          enabled: false
    bjj-frontend:
      frontend:
        replicaCount: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        podAnnotations:
          prometheus.io/scrape: "false"
        autoscaling:
          enabled: false
