---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bjj-eire
  namespace: bjj-app
spec:
  values:
    bjj-api:
      api:
        image:
          tag: v0.1.11 # {"$imagepolicy": "bjj-app:bjjeire-api:tag"}
    bjj-frontend:
      frontend:
        image:
          tag: v0.1.21 # {"$imagepolicy": "bjj-app:bjjeire-frontend:tag"}
    seeder:
      image:
        tag: v0.1.11 # {"$imagepolicy": "bjj-app:bjjeire-seeder:tag"}
