apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bjj-eire
  namespace: bjjeire-app
spec:
  values:
    bjj-api:
      api:
        image:
          tag: v0.1.13 # {"$imagepolicy": "bjjeire-app:bjjeire-api:tag"}
    bjj-frontend:
      frontend:
        image:
          tag: v0.1.25 # {"$imagepolicy": "bjjeire-app:bjjeire-frontend:tag"}
    seeder:
      image:
        tag: v0.1.13 # {"$imagepolicy": "bjjeire-app:bjjeire-seeder:tag"}
