---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bjj-app

resources:
  - ../../../base/bjj-eire/app

patches:
  - target:
      kind: OCIRepository
      name: bjj-eire
    patch: |
      - op: replace
        path: /spec/ref
        value:
          tag: "0.1.9"
