---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bjj-app

resources:
  - ../../../base/bjj-eire/app

patches:
  - target:
      kind: OCIRepository
      name: bjj-eire
    patch: |
      - op: replace
        path: /spec/ref
        value:
          tag: "0.1.7"
  - path: helmrelease-images.yaml
    target:
      kind: HelmRelease
      name: bjj-eire
  - path: helmrelease-dev-values.yaml
    target:
      kind: HelmRelease
      name: bjj-eire
  - patch: |
      $patch: delete
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDashboard
      metadata:
        name: bjj-eire-api
        namespace: bjj-app
    target:
      kind: GrafanaDashboard
  - patch: |
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: bjj-api
        namespace: bjj-app
    target:
      kind: ServiceMonitor
